version: 2

build:
    os: ubuntu-22.04
    tools:
        python: "3.10"

formats: all

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs: docs/source/requirements.txt


sphinx:
    builder: html
    configuration: docs/conf.py
    fail_on_warning: false